name: Pipeline for BeyoundDouble Project

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    name: Lint Java Code
    runs-on: ubuntu-latest
    container:
      image: gradle:8.5-jdk17-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Java Checkstyle
        run: ./gradlew checkstyleMain

  test:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest
    if: |
      github.ref_name == 'main' ||
      github.ref_name == 'develop' ||
      github.base_ref == 'main' ||
      github.base_ref == 'develop'
    container:
      image: gradle:8.5-jdk17-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests with coverage
        run: ./gradlew test jacocoTestReport

  build:
    name: Build Package
    runs-on: ubuntu-latest
    if: github.ref_name == 'main' || github.base_ref == 'main'
    container:
      image: gradle:8.5-jdk17-jammy
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Upload build artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/libs/*.jar

  docker:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    if: success() && (github.ref_name == 'main' || github.base_ref == 'main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t beyonddouble:latest -f .github/docker/Dockerfile .

      - name: Test Docker image
        run: |
          docker run --name test-container beyonddouble:latest
          docker logs test-container
          docker inspect test-container

      - name: Cleanup Docker
        if: always()
        run: docker rm -f test-container || true
